import type { Metadata } from "next";
import { SkipLink } from "@/components/layout/SkipLink";
import { NavBar } from "@/components/layout/NavBar";
import { Footer } from "@/components/layout/Footer";
import { LightboxProvider } from "@/components/ui/Lightbox";
import { site } from "@/content/site";
// Self-hosted variable fonts (no request to Google Fonts at build or
// runtime). "full.css" includes the optical-size axis Fraunces needs for
// its expressive display treatment at large sizes; Inter only needs its
// weight axis. Family names ("Inter Variable" / "Fraunces Variable") are
// referenced directly from the --font-sans / --font-display tokens in
// globals.css.
import "@fontsource-variable/inter";
import "@fontsource-variable/fraunces/full.css";
import "./globals.css";

const siteUrl = "https://aseer.design";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    // Middle dot, not an em dash -- matches the name/title separator
    // already used on-site (Eyebrow on the homepage hero, resume page).
    default: `${site.name} · ${site.title}`,
    template: `%s · ${site.name}`,
  },
  description: site.heroProofPoint,
  openGraph: {
    type: "website",
    url: siteUrl,
    siteName: site.name,
    title: `${site.name} · ${site.title}`,
    description: site.heroProofPoint,
  },
  twitter: {
    card: "summary_large_image",
    title: `${site.name} · ${site.title}`,
    description: site.heroProofPoint,
  },
  robots: {
    index: true,
    follow: true,
  },
  // Branding update: real designed mark (the "A" from the
  // Md. Aseer Intiser logo lockup), replacing the earlier placeholder
  // generated by app/icon.tsx. The full lockup also carries a fine
  // cursive "Intiser" signature crossing the crossbar, which reads as
  // noise at 16-32px, so the favicon crops to just the bold "A"
  // glyph -- unmodified path data, same brand colors -- rather than
  // shrinking the full wordmark. Assets live in public/ (not app/)
  // because file-based icon/favicon conventions in app/ take priority
  // over this metadata object and would silently override the
  // prefers-color-scheme switch below.
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon-light.svg", type: "image/svg+xml", media: "(prefers-color-scheme: light)" },
      { url: "/icon-dark.svg", type: "image/svg+xml", media: "(prefers-color-scheme: dark)" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {/* Functional grain, not decorative -- see globals.css .grain-overlay
            for the full rationale (prevents banding on flat color fields). */}
        <div className="grain-overlay" aria-hidden="true" />
        <SkipLink />
        <NavBar />
        {/* Media Experience milestone: mounted once here so every
            click-to-enlarge trigger anywhere in the app (CaseStudyImage,
            ImageRow, and anything added later) shares one overlay
            implementation instead of each rolling its own modal. */}
        <LightboxProvider>
          <main id="main-content">{children}</main>
        </LightboxProvider>
        <Footer />
      </body>
    </html>
  );
}
